#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.NoobWRT >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.NoobWRT=/luci-static/noobwrt
		set luci.main.mediaurlbase=/luci-static/noobwrt
		commit luci
	EOF
fi

exit 0
