#!/bin/sh
#=================================================
# Copyright (c) 2026 Lahiru S Liyanage (NoobLK) <liyanagelsofficial@gmail.com>
# GitHub: https://github.com/nooblk-98/luci-app-aw1k-led
# Telegram: @itsme_nooblk
# License: GPL-3.0-or-later
#=================================================

chmod +x /etc/init.d/ledstatus
chmod +x /usr/bin/led-status-check-daemon.sh
chmod +x /usr/bin/led-status-check.sh

/etc/init.d/ledstatus enable
/etc/init.d/ledstatus start
exit 0
