#!/bin/sh

if ! uci -q get uhttpd.main.listen_https >/dev/null; then
	uci -q add_list uhttpd.main.listen_https='0.0.0.0:443'
	uci -q add_list uhttpd.main.listen_https='[::]:443'
	uci -q commit uhttpd
fi

/etc/init.d/uhttpd restart
exit 0
